[build]
    command = "npm run build"
    publish = "/dist"
    base = "/"

[[redirects]]
    from ="/*"
    to = "/index.html"
    status = 200 

[[redirects]]
    from ="/signup"
    to = "/#/signup"
    status = 200 

[[redirects]]
    from ="/mainmenu*"
    to = "/#/mainmenu"
    status = 200 